checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: true
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: true
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: true
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        simplify_boolean_return: true
        uppercase_constants: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        no_goto: true
        return_doc_comments: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        prefer_while_loop_over_for_loop: true
        param_doc_comment_if_not_inferrable: true
        newline_at_end_of_file: true
        custom_coding_standard:
            ruleset_path: build/ruleset.xml
    javascript: true

filter:
    excluded_paths:
        - build/*
        - Tests/*

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: true
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: true
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: true
                else_on_new_line: false
            for:
                opening: end-of-line
                always: true
            while:
                opening: end-of-line
                always: true
            do_while:
                opening: end-of-line
                always: true
                while_on_new_line: false
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build:

    tests:
        override:
        -
            command: cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME} && vendor/phpunit/phpunit/phpunit --coverage-clover=/home/scrutinizer/build/clover-coverage
            coverage:
                file: clover-coverage
                format: clover

    environment:
        php:
            ini:
                'date.timezone': 'Europe/Berlin'
        postgresql:           false
        redis:                false
        variables:
            # This is the right way to define env vars, but vars are not replaced in the before commands
            # so we use export instead for now
            #BUILD_HOME: /home/scrutinizer
            #SHOPWARE_VERSION: 5.2
            #SHOPWARE_DIRECTORY: ${BUILD_HOME}/shopware
            #PLUGIN_NAME: FatchipCTPayment
            #PLUGIN_DIRECTORY: ${SHOPWARE_DIRECTORY}/engine/Shopware/Plugins/Community/Frontend

    dependencies:
        before:
            - export BUILD_HOME=/home/scrutinizer
            - export SHOPWARE_VERSION=5.2
            - export SHOPWARE_DIRECTORY=${BUILD_HOME}/shopware
            - export PLUGIN_NAME=FatchipCTPayment
            - export PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/engine/Shopware/Plugins/Community/Frontend
            - git submodule update --init --recursive --remote
            - git submodules sync
            - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
            - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=root -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
            - cp -R /home/scrutinizer/build ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
            - php ${BUILD_HOME}/shopware/bin/console sw:plugin:refresh
            - php ${BUILD_HOME}/shopware/bin/console sw:plugin:install ${PLUGIN_NAME}
            - php ${BUILD_HOME}/shopware/bin/console sw:plugin:activate ${PLUGIN_NAME}
            - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

    nodes:
        php56:
            environment:
                hosts:
                    local.dev: '127.0.0.1'
                php: 5.6
                apache2:
                    modules: ['rewrite']
                    sites:
                        shopware:
                            web_root: shopware
                            host: 'local.dev'

                mysql: 5.6

#            php70:
#                environment:
#                    php: 7.0
#                    apache2:
#                        modules: ['rewrite']
#                    mysql: 5.6

#            php71:
#                environment:
#                    php: 7.1
#                    apache2:
#                        modules: ['rewrite']
#                    mysql: 5.6

#            php72:
#                environment:
#                    php: 7.2
#                    apache2:
#                        modules: ['rewrite']
#                    mysql: 5.6